networks:
  br_docker_overlay:
    external: true

services:
  hawser:
    image: 'ghcr.io/finsys/hawser'
    networks:
      - br_docker_overlay
    container_name: hawser_edge
    restart: unless-stopped
    environment:
      # run nginx proxy manager first
      - DOCKHAND_SERVER_URL=${DOCKHAND_SERVER_URL}
      - TOKEN=${HAWSER_TOKEN}
        #- TOKEN=$HAWSER_TOKEN
      - AGENT_NAME=br-qa-server
        #- LOG_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /srv/br_docker/stacks:/srv/br_docker/stacks
